export const IngEventData=[
  {
    id:1,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent1.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:2,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent2.png",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:3,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent3.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:4,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent4.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:5,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent5.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:6,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent6.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:7,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent7.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  },
  {
    id:8,
    alt:"이벤트 이미지",
    imgUrl:"/images/ingevent8.jpg",
    url:"/ingevents",
    title:"맘키즈클럽 플러스 행사상품 안내(8월 2차)",
    regdate:"2023-08-16 ~ 08-31",
  }
]